# Generated by Django 5.2.8 on 2025-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(default='Queen', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
